spring:
  datasource:
    url: jdbc:mysql://192.168.31.40:3306/fiveup?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 963578
  redis:
    host: 192.168.31.40 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  elasticsearch:
    rest:
      uris: http://localhost:9200

logging:
  level:
    root: info
    com.elk.exam: debug

logstash:
  host: localhost
